/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spminiproject.lab3;

import java.util.Scanner;

/**
 *
 * @author Samsung
 */
public class GroupedJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GroupedJFrame
     */
    public GroupedJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        desc.setText("                     DESCRIPTION");
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel1.add(desc);
        desc.setBounds(30, 50, 210, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GROUPED");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 20, 90, 22);

        jButton1.setText("integer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 90, 160, 50);

        jButton2.setText("float");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 170, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmsc105lab3/blu.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 270, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Scanner input = new Scanner(System.in);
        
        int choice, type, pop, int_datum;
        float float_datum;
        String des = desc.getText();
        int intervalnum = 0,OpenorClose = 0, w_interval = 0;
        
        do{
            try{
                System.out.print("No. of class intervals(minimum=3): ");
                intervalnum = input.nextInt();
                
                if(intervalnum < 3){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                intervalnum = -1;
            }
            
            input.nextLine();
        }while(intervalnum == -1);
        
        Grouped test1 = new Grouped(intervalnum);
        test1.desc = des;
        
        do{
            try{
                System.out.print("Open-ended(1) or Close-ended(2): ");
                OpenorClose = input.nextInt();
                
                if(OpenorClose < 1 || OpenorClose > 2){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                OpenorClose = -1;
            }
            input.nextLine();
        }while(OpenorClose == -1);
        
        if(OpenorClose == 1){
            do{
                try{
                    System.out.print("first(1), last interval(2) or both(3): ");
                    w_interval = input.nextInt();
                }catch(Exception e){
                    System.out.println("You entered an invalid input. Please try again!");
                    w_interval = -1;
                }
                input.nextLine();
            }while(w_interval == -1);
        }
        
        for(int i = 0; i < test1.data.length; i++){
            
            if( (w_interval == 1 || w_interval ==3) && i == 0){
                System.out.println("Interval "+ (i+1) +" " );
                System.out.println("LCL: -- ");
                test1.data[i][0] = -1;
                
                do{
                    try{
                        System.out.print("UCL: ");
                        test1.data[i][1] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][1])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][1] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][1] == -1);
                
                do{
                    try{
                        System.out.print("Frequency: ");
                        test1.data[i][2] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][2])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][2] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][2] == -1);
                
                
                test1.data[i][3] = -1;
                test1.data[i][4] = -1;
                test1.data[i][5] = -1;
            }
            else if( (w_interval == 2 || w_interval == 3)&& i == (test1.data.length-1) ){
                System.out.println("Interval "+ (i+1) +" " );
                do{
                    try{
                        System.out.print("LCL: ");
                        test1.data[i][0] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][0])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][0] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][0] == -1);
                
                
                System.out.println("UCL: --");
                test1.data[i][1] = -1;
                
                do{
                    try{
                        System.out.print("Frequency: ");
                        test1.data[i][2] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][2])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][2] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][2] == -1);
                
                
                test1.data[i][3] = -1;
                test1.data[i][4] = -1;
                test1.data[i][5] = -1;
            }
            else{
                System.out.println("Interval "+ (i+1) +" " );
                do{
                    try{
                        System.out.print("LCL: ");
                        test1.data[i][0] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][0])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][0] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][0] == -1);
                
                do{
                    try{
                        System.out.print("UCL: ");
                        test1.data[i][1] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][1])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][1] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][0] == -1);
                
                do{
                    try{
                        System.out.print("Frequency: ");
                        test1.data[i][2] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][2])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][2] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][2] == -1);
                
                
                test1.data[i][3] = (test1.data[i][0] + test1.data[i][1]) / 2;
                test1.data[i][4] = test1.data[i][2] * test1.data[i][3];
                test1.data[i][5] = test1.data[i][4] * test1.data[i][3];
            }
        }
        
        int choice4 = 0,index4 = 0,w_interval2= 0;
        do{
            try{
                System.out.print("Edit(1) or Continue(2):  ");
                choice4 = input.nextInt();
            }catch(Exception e){
                choice4 = 3;
            }
            if(choice4 == 1){
                do{
                    try{
                        System.out.println(intervalnum);
                        System.out.print("At what interval: ");
                        w_interval2 = input.nextInt();
                        
                        if(w_interval < 1 || w_interval > intervalnum){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        w_interval2 = -1;
                    }
                    input.nextLine();
                }while(w_interval2 == -1);
                
                if(w_interval2 == 1 && (w_interval == 1 || w_interval == 3)){
                    
                    System.out.println("Interval "+ w_interval2 +" " );
                    System.out.println("LCL: -- ");
                    test1.data[w_interval2 -1][0] = -1;
                    do{
                        try{
                            System.out.print("UCL: ");
                            test1.data[w_interval2-1][1] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][1])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][1] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][1] == -1);
                    
                    do{
                        try{
                            System.out.print("Frequency: ");
                            test1.data[w_interval2-1][2] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][2])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][2] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][2] == -1);
                    
                    
                    test1.data[w_interval2-1][3] = -1;                            
                    test1.data[w_interval2-1][4] = -1;                            
                    test1.data[w_interval2-1][5] = -1;
                }
                
                else if(w_interval2 == test1.data.length && (w_interval == 1 || w_interval == 3)){
                    System.out.print("Interval "+ w_interval2 +" " );
                    do{
                        try{
                            System.out.print("LCL: ");
                            test1.data[w_interval2 -1][0] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][0])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2 -1][0] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2 -1][0] == -1);
                    
                    System.out.println("UCL: --");
                    test1.data[w_interval2 -1][1] = -1;
                    
                    do{
                        try{
                            System.out.print("Frequency: ");
                            test1.data[w_interval2 -1][2] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][2])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2 -1][2] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2 -1][2] == -1);
                    
                    
                    test1.data[w_interval2 -1][3] = -1;
                    test1.data[w_interval2 -1][4] = -1;
                    test1.data[w_interval2 -1][5] = -1;
                }
                else{
                    System.out.println("Interval "+ w_interval2 +" " );
                    do{
                        try{
                            System.out.print("LCL: ");
                            test1.data[w_interval2-1][0] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][0])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][0] = -1;
                        }
                    }while(test1.data[w_interval2-1][0] == -1);
                    
                    
                    do{
                        try{
                            System.out.print("UCL: ");
                            test1.data[w_interval2-1][1] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][1])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][1] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][1] == -1);
                   
                    do{
                        try{
                            System.out.print("Frequency: ");  
                            test1.data[w_interval2-1][2] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][2])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][2] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][2] == -1);
                    
                    test1.data[w_interval2-1][3] = (test1.data[w_interval2-1][0] + test1.data[w_interval2-1][1]) / 2;                           
                    test1.data[w_interval2-1][4] = test1.data[w_interval2-1][2] * test1.data[w_interval2-1][3];               
                    test1.data[w_interval2-1][5] = test1.data[w_interval2-1][4] * test1.data[w_interval2-1][3];
                }
            }
            else if(choice4 != 2){  
                System.out.println("Wrong input.");      
            }
            input.nextLine();
        }while(choice4 != 2);
        test1.display();
        int choice5 = 0;
        
        System.out.println("\n Measures of Central Tendency");
        System.out.println("1. Mean");
        System.out.println("2. Median");
        System.out.println("3. Mode");
        System.out.println("4. all");
        System.out.println("5. continue");
        
        String interp = "";
        do{
            try{
                System.out.print("Enter the number of what you want to display: ");
                choice5 = input.nextInt();
                
                if(choice5 <1 || choice5 >5){
                    throw new Exception();
                }
                
                if(choice5 == 1){
                    test1.Mean(OpenorClose);
                }
                else if(choice5 == 2){
                    test1.Median();
                }
                else if(choice5 == 3){
                    test1.getMode();
                }
                else if(choice5 == 4){
                    test1.Mean(OpenorClose);
                    test1.Median();
                    test1.getMode();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                choice5 = -1;
            }    
        }while(choice5 != 5);
        input.nextLine();
        System.out.println("INTERPRETATION: ");
        interp = input.nextLine();
        
        test1.display(interp);
        
        input.nextLine();
        new cmsc105lab3GUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Scanner input = new Scanner(System.in);
        
        int choice, type, pop, int_datum;
        float float_datum;
        String des = desc.getText();
        int intervalnum = 0,OpenorClose = 0, w_interval = 0;
        
        do{
            try{
                System.out.print("No. of class intervals(minimum=3): ");
                intervalnum = input.nextInt();
                
                if(intervalnum < 3){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                intervalnum = -1;
            }
            
            input.nextLine();
        }while(intervalnum == -1);
        
        Grouped test1 = new Grouped(intervalnum);
        test1.desc = des;
        
        do{
            try{
                System.out.print("Open-ended(1) or Close-ended(2): ");
                OpenorClose = input.nextInt();
                
                if(OpenorClose < 1 || OpenorClose > 2){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                OpenorClose = -1;
            }
            input.nextLine();
        }while(OpenorClose == -1);
        
        if(OpenorClose == 1){
            do{
                try{
                    System.out.print("first(1), last interval(2) or both(3): ");
                    w_interval = input.nextInt();
                }catch(Exception e){
                    System.out.println("You entered an invalid input. Please try again!");
                    w_interval = -1;
                }
                input.nextLine();
            }while(w_interval == -1);
        }
        
        for(int i = 0; i < test1.data.length; i++){
            
            if( (w_interval == 1 || w_interval ==3) && i == 0){
                System.out.println("Interval "+ (i+1) +" " );
                System.out.println("LCL: -- ");
                test1.data[i][0] = -1;
                
                do{
                    try{
                        System.out.print("UCL: ");
                        test1.data[i][1] = input.nextFloat();
                        if(test1.isInteger(test1.data[i][1])){
                            throw new Exception();
                        }
                        
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][1] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][1] == -1);
                
                do{
                    try{
                        System.out.print("Frequency: ");
                        test1.data[i][2] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][2])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][2] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][2] == -1);
                
                
                test1.data[i][3] = -1;
                test1.data[i][4] = -1;
                test1.data[i][5] = -1;
            }
            else if( (w_interval == 2 || w_interval == 3)&& i == (test1.data.length-1) ){
                System.out.println("Interval "+ (i+1) +" " );
                do{
                    try{
                        System.out.print("LCL: ");
                        test1.data[i][0] = input.nextFloat();
                        if(test1.isInteger(test1.data[i][0])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][0] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][0] == -1);
                
                
                System.out.println("UCL: --");
                test1.data[i][1] = -1;
                
                do{
                    try{
                        System.out.print("Frequency: ");
                        test1.data[i][2] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][2])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][2] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][2] == -1);
                
                
                test1.data[i][3] = -1;
                test1.data[i][4] = -1;
                test1.data[i][5] = -1;
            }
            else{
                System.out.println("Interval "+ (i+1) +" " );
                do{
                    try{
                        System.out.print("LCL: ");
                        test1.data[i][0] = input.nextFloat();
                        if(test1.isInteger(test1.data[i][0])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][0] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][0] == -1);
                
                do{
                    try{
                        System.out.print("UCL: ");
                        test1.data[i][1] = input.nextFloat();
                        if(test1.isInteger(test1.data[i][1])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][1] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][0] == -1);
                
                do{
                    try{
                        System.out.print("Frequency: ");
                        test1.data[i][2] = input.nextFloat();
                        if(test1.isFloating(test1.data[i][2])){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        test1.data[i][2] = -1;
                    }
                    input.nextLine();
                }while(test1.data[i][2] == -1);
                
                
                test1.data[i][3] = (test1.data[i][0] + test1.data[i][1]) / 2;
                test1.data[i][4] = test1.data[i][2] * test1.data[i][3];
                test1.data[i][5] = test1.data[i][4] * test1.data[i][3];
            }
        }
        
        int choice4 = 0,index4 = 0,w_interval2= 0;
        do{
            try{
                System.out.print("Edit(1) or Continue(2):  ");
                choice4 = input.nextInt();
            }catch(Exception e){
                choice4 = 3;
            }
            if(choice4 == 1){
                do{
                    try{
                        System.out.println(intervalnum);
                        System.out.print("At what interval: ");
                        w_interval2 = input.nextInt();
                        
                        if(w_interval < 1 || w_interval > intervalnum){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        w_interval2 = -1;
                    }
                    input.nextLine();
                }while(w_interval2 == -1);
                
                if(w_interval2 == 1 && (w_interval == 1 || w_interval == 3)){
                    
                    System.out.println("Interval "+ w_interval2 +" " );
                    System.out.println("LCL: -- ");
                    test1.data[w_interval2 -1][0] = -1;
                    do{
                        try{
                            System.out.print("UCL: ");
                            test1.data[w_interval2-1][1] = input.nextFloat();
                            if(test1.isInteger(test1.data[w_interval2-1][1])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][1] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][1] == -1);
                    
                    do{
                        try{
                            System.out.print("Frequency: ");
                            test1.data[w_interval2-1][2] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][1])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][2] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][2] == -1);
                    
                    
                    test1.data[w_interval2-1][3] = -1;                            
                    test1.data[w_interval2-1][4] = -1;                            
                    test1.data[w_interval2-1][5] = -1;
                }
                
                else if(w_interval2 == test1.data.length && (w_interval == 1 || w_interval == 3)){
                    System.out.print("Interval "+ w_interval2 +" " );
                    do{
                        try{
                            System.out.print("LCL: ");
                            test1.data[w_interval2 -1][0] = input.nextFloat();
                            if(test1.isInteger(test1.data[w_interval2-1][0])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2 -1][0] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2 -1][0] == -1);
                    
                    System.out.println("UCL: --");
                    test1.data[w_interval2 -1][1] = -1;
                    
                    do{
                        try{
                            System.out.print("Frequency: ");
                            test1.data[w_interval2 -1][2] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][2])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2 -1][2] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2 -1][2] == -1);
                    
                    
                    test1.data[w_interval2 -1][3] = -1;
                    test1.data[w_interval2 -1][4] = -1;
                    test1.data[w_interval2 -1][5] = -1;
                }
                else{
                    System.out.println("Interval "+ w_interval2 +" " );
                    do{
                        try{
                            System.out.print("LCL: ");
                            test1.data[w_interval2-1][0] = input.nextFloat();
                            if(test1.isInteger(test1.data[w_interval2-1][0])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][0] = -1;
                        }
                    }while(test1.data[w_interval2-1][0] == -1);
                    
                    
                    do{
                        try{
                            System.out.print("UCL: ");
                            test1.data[w_interval2-1][1] = input.nextFloat();
                            if(test1.isInteger(test1.data[w_interval2-1][1])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][1] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][1] == -1);
                   
                    do{
                        try{
                            System.out.print("Frequency: ");  
                            test1.data[w_interval2-1][2] = input.nextFloat();
                            if(test1.isFloating(test1.data[w_interval2-1][2])){
                                throw new Exception();
                            }
                        }catch(Exception e){
                            System.out.println("You entered an invalid input. Please try again!");
                            test1.data[w_interval2-1][2] = -1;
                        }
                        input.nextLine();
                    }while(test1.data[w_interval2-1][2] == -1);
                    
                    test1.data[w_interval2-1][3] = (test1.data[w_interval2-1][0] + test1.data[w_interval2-1][1]) / 2;                           
                    test1.data[w_interval2-1][4] = test1.data[w_interval2-1][2] * test1.data[w_interval2-1][3];               
                    test1.data[w_interval2-1][5] = test1.data[w_interval2-1][4] * test1.data[w_interval2-1][3];
                }
            }
            else if(choice4 != 2){  
                System.out.println("Wrong input.");      
            }
            input.nextLine();
        }while(choice4 != 2);
        test1.display();
        int choice5 = 0;
        
        System.out.println("\n Measures of Central Tendency");
        System.out.println("1. Mean");
        System.out.println("2. Median");
        System.out.println("3. Mode");
        System.out.println("4. all");
        System.out.println("5. continue");
        
        String interp = "";
        do{
            try{
                System.out.print("Enter the number of what you want to display: ");
                choice5 = input.nextInt();
                
                if(choice5 <1 || choice5 >5){
                    throw new Exception();
                }
                
                if(choice5 == 1){
                    test1.Mean(OpenorClose);
                }
                else if(choice5 == 2){
                    test1.Median();
                }
                else if(choice5 == 3){
                    test1.getMode();
                }
                else if(choice5 == 4){
                    test1.Mean(OpenorClose);
                    test1.Median();
                    test1.getMode();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                choice5 = -1;
            }    
        }while(choice5 != 5);
        input.nextLine();
        System.out.println("INTERPRETATION: ");
        interp = input.nextLine();
        
        test1.display(interp);
        
        input.nextLine();
        new cmsc105lab3GUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupedJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
