/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spminiproject.lab3;

import java.util.Scanner;

/**
 *
 * @author Samsung
 */
public class UngroupedJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UngroupedJFrame
     */
    public UngroupedJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        desc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        desc.setText("                      DESCRIPTION");
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel2.add(desc);
        desc.setBounds(29, 50, 200, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("UNGROUPED");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 20, 110, 20);

        jButton3.setText("integer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(50, 90, 160, 50);

        jButton4.setText("float");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(50, 170, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmsc105lab3/blu.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 250, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Scanner input = new Scanner(System.in);
        
        int choice, type, pop, int_datum;
        float float_datum;
        String des = desc.getText();
        Ungrouped test = new Ungrouped();
        do{
            try{
                System.out.print("Enter number of data(minimum = 5): ");
                pop  = input.nextInt();
                if(pop < 5){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                pop = - 1;
            }
            input.nextLine();
        }while(pop == -1);
        
        test = new Ungrouped(1);
        test.init_Description(des);
        
        System.out.println("UNGROUPED: " + test.description+"\n");
        
        for(int i = 0; i < pop; i++){
            try{
                System.out.print("Sample "+ (i+1) + ": ");
                float_datum = input.nextFloat();
                if(test.isFloating(float_datum)){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                float_datum = -100;
                input.nextLine();
                i = i-1;
            }
            if(float_datum != -100){
                test.ungrouped.add(float_datum);
            }
        }
                    
        test.display();
        int choice2 = 0,index2 = 0;
                    
        do{
            try{
                System.out.print("Edit(1) or Continue(2):  ");
                choice2 = input.nextInt();
                        
            }catch(Exception e){
                choice2 = 3;
            }
            
            if(choice2 == 1){
                do{
                    try{
                        System.out.print("Enter index(1 - "+pop+ " ):");
                        index2 = input.nextInt();
                        
                        if(index2 < 1 || index2 > pop){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid. Please try again! ");
                        index2 = -1;
                    }
                    input.nextLine();
                }while(index2 == -1);
                
                do{
                    try{
                        System.out.print("Enter value: ");
                        float_datum = input.nextFloat();
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        float_datum = -100;
                    }
                    input.nextLine();
                }while(float_datum == -100);
                
                test.EditDatum(index2, float_datum);
                test.display();
            
            }
                        
            else if(choice2 != 2){
                System.out.println("Wrong input.");
            }
            input.nextLine();
        }while(choice2 != 2);
        
        int choice3 = 0;

        System.out.println("\n Measures of Central Tendency");
        System.out.println("1. Mean");
        System.out.println("2. Median");
        System.out.println("3. Mode");
        System.out.println("4. all");
        System.out.println("5. continue");
        
        String interp = "";
        do{
            try{
                System.out.print("Enter the number of what you want to display: ");
                choice3 = input.nextInt();
                
                if(choice3 <1 || choice3 >5){
                    throw new Exception();
                }
                
                if(choice3 == 1){
                    test.Mean();
                }
                else if(choice3 == 2){
                    test.Median();
                }
                else if(choice3 == 3){
                    test.Mode();
                }
                else if(choice3 == 4){
                    test.Mean();
                    test.Median();
                    test.Mode();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                choice3 = -1;
            }    
        }while(choice3 != 5);
        input.nextLine();
        System.out.println("INTERPRETATION: ");
        interp = input.nextLine();
        test.display(interp);
        
        input.nextLine();
        new cmsc105lab3GUI().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Scanner input = new Scanner(System.in);
        
        int choice, type, pop, int_datum;
        float float_datum;
        String des = desc.getText();
        Ungrouped test = new Ungrouped();
        do{
            try{
                System.out.print("Enter number of data(minimum = 5): ");
                pop  = input.nextInt();
                if(pop < 5){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                pop = - 1;
            }
            input.nextLine();
        }while(pop == -1);
        
        test = new Ungrouped(2);
        test.init_Description(des);
        
        System.out.println("UNGROUPED: " + test.description+"\n");
        for(int i = 0; i < pop; i++){
            try{
                System.out.print("Sample "+ (i+1) + ": ");
                float_datum = input.nextFloat();
                
                if(test.isInteger(float_datum)){
                    throw new Exception();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                float_datum = -100;
                input.nextLine();
                i = i-1;
            }
            if(float_datum != -100)
                test.ungrouped.add(float_datum);
        }
        test.display();
        int choice2 = 0,index2 = 0;
        do{
            try{
                System.out.print("Edit(1) or Continue(2):  ");
                choice2 = input.nextInt();
            }catch(Exception e){
                choice2 = 3;
            }
            
            if(choice2 == 1){
                do{
                    try{
                        System.out.print("Enter index(1 - "+pop+ " ):");
                        index2 = input.nextInt();
                        if(index2 < 1 || index2 > pop){
                            throw new Exception();
                        }
                    }catch(Exception e){
                        System.out.println("You entered an invalid. Please try again! ");
                        index2 = -1;
                    }
                    input.nextLine();
                }while(index2 == -1);
                
                do{
                    try{
                        System.out.print("Enter value: ");
                        float_datum = input.nextFloat();
                    }catch(Exception e){
                        System.out.println("You entered an invalid input. Please try again!");
                        float_datum = -100;
                    }
                    input.nextLine();
                }while(float_datum == -100);
                
                test.EditDatum(index2, float_datum);
                
                test.display();
            }
            
            else if(choice2 != 2){
                System.out.println("Wrong input.");
            }
            input.nextLine();
        }while(choice2 != 2);
        int choice3 = 0;
        
        System.out.println("\n Measures of Central Tendency");
        System.out.println("1. Mean");
        System.out.println("2. Median");
        System.out.println("3. Mode");
        System.out.println("4. all");
        System.out.println("5. continue");
        
        String interp = "";
        do{
            try{
                System.out.print("Enter the number of what you want to display: ");
                choice3 = input.nextInt();
                
                if(choice3 <1 || choice3 >5){
                    throw new Exception();
                }
                
                if(choice3 == 1){
                    test.Mean();
                }
                else if(choice3 == 2){
                    test.Median();
                }
                else if(choice3 == 3){
                    test.Mode();
                }
                else if(choice3 == 4){
                    test.Mean();
                    test.Median();
                    test.Mode();
                }
            }catch(Exception e){
                System.out.println("You entered an invalid input. Please try again!");
                choice3 = -1;
            }    
        }while(choice3 != 5);
        input.nextLine();
        System.out.println("INTERPRETATION: ");
        interp = input.nextLine();
        
        test.display(interp);
        
        input.nextLine();
        new cmsc105lab3GUI().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UngroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UngroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UngroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UngroupedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UngroupedJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
